### ISSUE TITLE
Error on first command

### ISSUE THREAD

**Issue by zaisahil** [ant-vel/App#1]
Hi, I was trying to follow your step as mentioned in the read me file. 

I am getting an error while I am running your first command:
 composer require ant-vel/ant-vel

**Error:**
Saeed Nawaz@DESKTOP-JL4E89M MINGW64 /c/xampp/htdocs/dev
$ composer require ant-vel/ant-vel
Using version ^1.0 for ant-vel/ant-vel
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - ant-vel/ant-vel v1.0.3 requires greggilbert/recaptcha dev-master@dev -> satisfiable by greggilbert/recaptcha[dev-master] but these conflict with your requirements or minimum-stability.
    - ant-vel/ant-vel v1.0.2 requires greggilbert/recaptcha dev-master -> satisfiable by greggilbert/recaptcha[dev-master] but these conflict with your requirements or minimum-stability.
    - ant-vel/ant-vel v1.0.1 requires gloudemans/shoppingcart dev-master -> satisfiable by gloudemans/shoppingcart[dev-master] but these conflict with your requirements or minimum-stability.
    - ant-vel/ant-vel v1.0 requires gloudemans/shoppingcart dev-master -> satisfiable by gloudemans/shoppingcart[dev-master] but these conflict with your requirements or minimum-stability.
    - Installation request for ant-vel/ant-vel ^1.0 -> satisfiable by ant-vel/ant-vel[v1.0, v1.0.1, v1.0.2, v1.0.3].

Installation failed, deleting ./composer.json.

![screenshot-2017-03-16](https://cloud.githubusercontent.com/assets/13915739/23982724/13949300-0a31-11e7-89cd-eb78640f9c14.png)

**Comment by gocanto** [comment]
Did u try cloning the repo? This is something i still need to figure out

**Comment by zaisahil** [comment]
Yes I tried to clone the repo and in that I got the some error which I mentioned in a separate issue to keep things easy and clear to understand.

**Comment by gocanto** [comment]
The composer installation is broken at the moment. Wanna send a PR?
