### ISSUE TITLE
Migration errors while installing on Win 

### ISSUE THREAD

**Issue by cent040** [ant-vel/App#10]
here is the error 
 [RuntimeException]                                                                                                                                                                            
  Source path "/Users/Gustavo/Documents/VALET/Antvel/Shop" is not found for pack                                                                                                                age antvel/shop

**Comment by cent040** [comment]
I update composer like again after error `composer update` and seem like start working now. thanks

**Comment by cent040** [comment]
migration error now.. 

 Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to
 use
  near 'json null, `confirmation_token` varchar(100) null, `remember_token` varchar(100)' at line 1

**Comment by gocanto** [comment]
Hey buddy, can you point to the migration that is giving this error? I use mysql, so I have not seen this error before.

**Comment by cent040** [comment]
I am also using mysql. 
here is the error 

**Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to
use
near 'json null, confirmation_token varchar(100) null, remember_token varchar(100)' at line 1**

i can see users create table in migration

thanks

**Comment by gocanto** [comment]
What version are you using? it seems to be related version issues.

**Comment by cent040** [comment]
mysqlnd 5.0.12-dev - 20150407

**Comment by gocanto** [comment]
I am pretty sure it might be a version issue. I will research this today and try to come back to you as soon as I can. If you happen to find something, let me know.

**Comment by cent040** [comment]
thanks

**Comment by cent040** [comment]
Hi, Can you upload .sql file. that is very much ease for windows and cpanel users. the users that not use command line. thanks

**Comment by gocanto** [comment]
[antvel_2017-04-08.sql.zip](https://github.com/ant-vel/App/files/907692/antvel_2017-04-08.sql.zip)
