### ISSUE TITLE
Access denied for user 'roo'@localhost (using password: YES)

### ISSUE THREAD

**Issue by Kolovrat19** [ant-vel/App#13]
Can you remove the password from the .env.example? Thank you.

**Comment by gocanto** [comment]
Will do tonight.

**Comment by Kolovrat19** [comment]
Can be use Nested SET Model in CategoriesController? https://en.wikipedia.org/wiki/Nested_set_model. This model perfectly builds a tree of categories. You can use https://github.com/etrepat/baum. In my big projects this package works fine. Good luck.

**Comment by gocanto** [comment]
Hey thanks for sharing. Actually, I am working in the products list refactor. I will certainly take a look at this. 

Thanks for testing.

**Comment by gocanto** [comment]
fixed on https://github.com/ant-vel/App/commit/1a6c609fec322c20322f515cf3bb6faa9ee3a61e

**Comment by napestershine** [comment]
HI @gocanto 

I am getting same error. Can you please fix it. Thanks
