### ISSUE TITLE
Error while running php artisan migrate

### ISSUE THREAD

**Issue by Cejowisz** [ant-vel/App#15]
I got error while trying to migrate the database.

Attached is the error screenshot.

![error](https://cloud.githubusercontent.com/assets/5602693/25556937/dc1775f0-2cfe-11e7-8cc8-a84087bc7f73.PNG)

**Comment by gocanto** [comment]
Duplicated, 

I will try to have this issue centralized over https://github.com/ant-vel/Antvel/issues/249

**Comment by gocanto** [comment]
Closed due to https://mariadb.com/resources/blog/json-mariadb-102
