### ISSUE TITLE
Ant-vel installer not running in composer

### ISSUE THREAD

**Issue by ridislam** [ant-vel/App#16]
[InvalidArgumentException]
  Could not find package antvel/installer at any version matching your PHP ve
  rsion 5.6.27.0

**Comment by gocanto** [comment]
What PHP version do you have? 

The store is built to run under https://github.com/ant-vel/Shop/blob/master/composer.json#L23

**Comment by ridislam** [comment]
i was using 5.6.27, then i have upgraded the php version to 7. but then another error occurred, while migrating tables, can you tell me is their any process for install manually ?

**Comment by ridislam** [comment]
and the migration error is in user table migration file line 41 where you used enum table format, please check that issue, and in installer you used no password for root, is their any way to install using root password. if yes then how..?

**Comment by Kolovrat19** [comment]
User table exists by default for Laravel. Do you have it?

**Comment by gocanto** [comment]
Can I see the error you are having? It is really difficult for me to know what's going on if I do mot see. Also, provide me the OS you have and how you are trying to install it. 

Thanks for testing

**Comment by gocanto** [comment]
ping @Kolovrat19 @ridislam

**Comment by ridislam** [comment]
> exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected 'default' (T_DEFAULT)' in /Applications/MAMP/htdocs/ant-vel/App-master/vendor/antvel/shop/database/migrations/2014_10_12_000000_create_users_table.php:41

this the error log from laravel.log file, you have used a deprecated table column type in this line. $table->enum
and i am using mac os sierra
@gocanto

**Comment by gocanto** [comment]
will check carefully then.

**Comment by percymamedy** [comment]
@ridislam Illuminate\Database\Schema\Blueprint enum is not deprecated!!...
