### ISSUE TITLE
someplace is different with the demo website 

### ISSUE THREAD

**Issue by humengtao** [ant-vel/App#19]
there are some bugs in this app but the demo website is fine,I don't know why ? is that is different between online and demo?

**Comment by gocanto** [comment]
Can tou provide a list with them? I will be glad get rid of them.

Githup and online use the same code.

**Comment by ridislam** [comment]
brother the main problem is the installation is not much developer friendly, if possible then keep it more user friendly and keep a manual way to install it.

**Comment by gocanto** [comment]
Do you have any suggestion?

**Comment by humengtao** [comment]
its too many to be listed ，I'v been starting to code a new shopping project,I will continue help you fix some issues when my shopping is completely coded
