### ISSUE TITLE
Error on running php artisan migrate:refresh

### ISSUE THREAD

**Issue by zaisahil** [ant-vel/App#2]
Hi, I tried to clone the whole source, and once I run 

> php artisan migrate:refresh

 I get the following error:

> Saeed Nawaz@DESKTOP-JL4E89M MINGW64 /c/xampp/htdocs/dev/antVel (master)
> $ php artisan migrate:refresh
> Nothing to rollback.
> 
> 
>   [Illuminate\Database\QueryException]
>   SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use
>   near 'json null, `remember_token` varchar(100) null, `created_at` timestamp null, `upd' at line 1 (SQL: create table `users` (`id` int unsigned not null auto_increment primary key, `nickn
>   ame` varchar(255) not null, `email` varchar(255) not null, `password` varchar(60) not null, `pic_url` varchar(255) null, `language` varchar(255) not null default 'en', `mobile_phone` varc
>   har(255) null, `work_phone` varchar(255) null, `website` varchar(255) null, `twitter` varchar(255) null, `facebook` varchar(255) null, `description` varchar(255) null, `time_zone` varchar
>   (255) null, `rate_val` int null, `rate_count` int null, `role` enum('admin', 'business', 'nonprofit', 'person') not null default 'person', `type` enum('normal', 'trusted') not null defaul
>   t 'normal', `verified` enum('yes', 'no') not null default 'no', `preferences` json null, `remember_token` varchar(100) null, `created_at` timestamp null, `updated_at` timestamp null, `dis
>   abled_at` timestamp null, `deleted_at` timestamp null) default character set utf8 collate utf8_unicode_ci)
> 
> 
> 
>   [PDOException]
>   SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use
>   near 'json null, `remember_token` varchar(100) null, `created_at` timestamp null, `upd' at line 1
> 
> 
> 
> Saeed Nawaz@DESKTOP-JL4E89M MINGW64 /c/xampp/htdocs/dev/antVel (master)
> 

Can you please check this out and let me know what I can do to fix this please? 

Thank you!

![image-2017-03-16-10-32-29](https://cloud.githubusercontent.com/assets/13915739/23983148/1dc967d0-0a34-11e7-98ba-da274a23e68b.png)

**Comment by gocanto** [comment]
What mysql version u have?

**Comment by zaisahil** [comment]
I am using the following version on my computer:

> Setting environment for using XAMPP for Windows.
> Saeed Nawaz@DESKTOP-JL4E89M c:\xampp
> # mysql --version
> mysql  Ver 15.1 Distrib 10.1.21-MariaDB, for Win32 (AMD64)
> 
> Saeed Nawaz@DESKTOP-JL4E89M c:\xampp

**Comment by gocanto** [comment]
This issue was addressed on https://github.com/ant-vel/Antvel/issues/107

Are you sure you have a compatible database for JSON fields?

**Comment by zaisahil** [comment]
Yes I am sure. And I see that the issue is addressed there but with no solution till now.

**Comment by gocanto** [comment]
that's just MySQL compatibilities.

**Comment by zaisahil** [comment]
How can we fix that?

**Comment by gocanto** [comment]
The issue here is the App is not a package, so I have to research how it can be done. I have not had the chance to work on it because I am doing a whole refactor.

**Comment by zaisahil** [comment]
Is it possible that you I can get a working copy of this eshop? And how?

**Comment by gocanto** [comment]
The App repository is working perfectly in my local machine, and it is the one posted on atvel.com.

Here is my settings: 

```
+-------------------------+-----------------------+
| Variable_name           | Value                 |
+-------------------------+-----------------------+
| innodb_version          | 5.7.12                |
| protocol_version        | 10                    |
| slave_type_conversions  |                       |
| tls_version             | TLSv1,TLSv1.1,TLSv1.2 |
| version                 | 5.7.12                |
| version_comment         | Homebrew              |
| version_compile_machine | x86_64                |
| version_compile_os      | osx10.11              |
+-------------------------+-----------------------+
```

**Comment by zaisahil** [comment]
I will check and update soon. Due to time difference, we are 12 hours ahead
and its 12 am mid night. I have to take some sleep.

**Comment by gocanto** [comment]
Did you get it working?

**Comment by gocanto** [comment]
Close on https://github.com/ant-vel/Installer
