### ISSUE TITLE
Installation problems. 

### ISSUE THREAD

**Issue by gocanto** [ant-vel/App#21]
I am opening this issue in order for us to keep centralized the installations problems that can appear. 

I am striving to get these bugs fixed out. Please, feel free to drop any suggestions I can use. 

I will appreciate your feedback.

**Comment by nodece** [comment]
i hope you fix mariadb problem
mariadb error:
![7292db1f-f917-4dc2-9997-bdf49e38e917](https://cloud.githubusercontent.com/assets/16235121/26239960/d4346f24-3cb1-11e7-86e5-a05164087ab1.png)

**Comment by i5on9i** [comment]
I have tried install on windows 10, but failed. the below is my output.
I think the problem is antvel installer does not have right 'require' package, (but just guess ;) )

`
C:\a\programming\php\antvel\src>composer require "antvel/installer" --dev
...
C:\a\programming\php\antvel\src>c:\a\programming\php\antvel\src\vendor\bin\antvel.bat install

PHP Fatal error:  Uncaught Error: Class 'Symfony\Component\Console\Application' not found in C:\a\programming\php\antvel\src\vendor\antvel\installer\antvel:9
Stack trace:
#0 {main}

thrown in C:\a\programming\php\antvel\src\vendor\antvel\installer\antvel on line 9

Fatal error: Uncaught Error: Class 'Symfony\Component\Console\Application' not found in C:\a\programming\php\antvel\src\vendor\antvel\installer\antvel on line 9

Error: Class 'Symfony\Component\Console\Application' not found in C:\a\programming\php\antvel\src\vendor\antvel\installer\antvel on line 9

Call Stack:
    0.4039     353568   1. {main}() C:\a\programming\php\antvel\src\vendor\antvel\installer\antvel:0
`

**Comment by gocanto** [comment]
Installing a VM with Win right now. I will start testing this installer.

**Comment by Farhanali5** [comment]
I was getting SQL PDO error. So I created a database named 'Antel' and now getting this error:
[Illuminate\Database\QueryException]
  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that
   corresponds to your MariaDB server version for the right syntax to use near 'json null, `confirmation_token` varch
  ar(60) null, `remember_token` varchar(100) ' at line 1 (SQL: create table `users` (`id` int unsigned not null auto_
  increment primary key, `nickname` varchar(60) not null, `email` varchar(100) not null, `password` varchar(60) not n
  ull, `pic_url` varchar(100) null, `language` varchar(10) not null default 'en', `mobile_phone` varchar(20) null, `w
  ork_phone` varchar(20) null, `website` varchar(100) null, `twitter` varchar(100) null, `facebook` varchar(100) null
  , `description` varchar(150) null, `time_zone` varchar(60) null, `rate_val` int null, `rate_count` int null, `role`
   enum('admin', 'business', 'person') not null default 'person', `type` enum('trusted', 'normal') not null default '
  normal', `verified` enum('yes', 'no') not null default 'no', `preferences` json null, `confirmation_token` varchar(
  60) null, `remember_token` varchar(100) null, `created_at` timestamp null, `updated_at` timestamp null, `disabled_a
  t` timestamp null, `deleted_at` timestamp null) default character set utf8mb4 collate utf8mb4_unicode_ci)



  [PDOException]
  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that
   corresponds to your MariaDB server version for the right syntax to use near 'json null, `confirmation_token` varch
  ar(60) null, `remember_token` varchar(100) ' at line 1


Please tell how to resolve this

**Comment by gocanto** [comment]
That error is due to your database version. Check previus closed issues.

**Comment by nodece** [comment]
@gocanto Which databases are supported by this application

**Comment by gocanto** [comment]
I have used mysql so far, but theroy, it might work with all the ones supported by Laravel.

**Comment by gocanto** [comment]
@nodece  The mariaDB issue is due to the ```JSON``` column type. They do not support it yet, so that's why you are seeing that error in your command line. Now, you can do two things, either fork the project and have your own implementation or change to ```mysql```. 

I do not plan to change the logic related to the particular ```JSON``` column in products for the time being.

**Comment by nodece** [comment]
@gocanto OK

**Comment by davisharry** [comment]
Hi, the same problem exits on another table... I just want to know how tables are going to be created while installing. It's the third time the same problem shows up..
![image](https://cloud.githubusercontent.com/assets/24517852/26684201/e6fd0d20-4718-11e7-9700-705305be016f.png)

**Comment by gocanto** [comment]
Just checked all the tables and fix their length https://github.com/ant-vel/App/commit/4a6c4e385fcb0155c54735ae10c23cb9f39fdb5b

If you still have the issue, let me know. Also, provide more info about your env, etc. 

thanks for testing.

**Comment by davisharry** [comment]
My dev env is wampserver 3.0.6 64bit  Mysql 5.7.14 php 7.0.10 apache 2.4.43

**Comment by gocanto** [comment]
Cool, let me know wheteher you still have the issue.

**Comment by Taufikur** [comment]
I got the same error with @Farhanali5 after i execute "antvel install"

error message:
[Illuminate\Database\QueryException]
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that
corresponds to your MariaDB server version for the right syntax to use near 'json null, confirmation_token varch
ar(60) null, remember_token varchar(100) ' at line 1 (SQL: create table users (id int unsigned not null auto_
increment primary key, nickname varchar(60) not null, email varchar(100) not null, password varchar(60) not n
ull, pic_url varchar(100) null, language varchar(10) not null default 'en', mobile_phone varchar(20) null, w ork_phone varchar(20) null, website varchar(100) null, twitter varchar(100) null, facebook varchar(100) null
, description varchar(150) null, time_zone varchar(60) null, rate_val int null, rate_count int null, role
enum('admin', 'business', 'person') not null default 'person', type enum('trusted', 'normal') not null default '
normal', verified enum('yes', 'no') not null default 'no', preferences json null, confirmation_token varchar(
60) null, remember_token varchar(100) null, created_at timestamp null, updated_at timestamp null, disabled_a t timestamp null, deleted_at timestamp null) default character set utf8mb4 collate utf8mb4_unicode_ci)

[PDOException]
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that
corresponds to your MariaDB server version for the right syntax to use near 'json null, confirmation_token varch
ar(60) null, remember_token varchar(100) ' at line 1

My XAMPP version : 7.1.4 
MariaDB version : 10.1.22

Please tell me how to resolve this
Thanks

**Comment by gocanto** [comment]
https://github.com/ant-vel/App/issues/15

**Comment by Taufikur** [comment]
So, what should I do?

**Comment by gocanto** [comment]
Either fork the project and have ur owm implementation or use mysql. 

Maybe mariadb will implement json soon
