### ISSUE TITLE
when I place an order , I got a error .

### ISSUE THREAD

**Issue by liron-li** [ant-vel/App#23]
sorry my english is very poor!

I locate the error here:
https://github.com/ant-vel/App/blob/master/app/Notice.php#L76

call `parent::create($attr)` throw errors

errors detail:
```
2017/05/24 07:59:33 [error] 1787#1787: *3342 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 20480 bytes) in /var/www/shop/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/GuardsAttributes.php on line 188
```

**Comment by gocanto** [comment]
working on it at the moment.

**Comment by gocanto** [comment]
Can you tell me how you environment was? I am not able to reproduce this.

**Comment by gocanto** [comment]
Fixed

**Comment by liron-li** [comment]
thx 
![image](https://cloud.githubusercontent.com/assets/24496043/26484184/5297130a-4223-11e7-8cc5-bbb9a88c2b76.png)
