### ISSUE TITLE
frontend assets not found

### ISSUE THREAD

**Issue by ridislam** [ant-vel/App#24]
<img width="1274" alt="screen shot 2017-05-26 at 8 15 28 am" src="https://cloud.githubusercontent.com/assets/7835820/26478083/a4fc5624-41eb-11e7-9bc1-c1e0c1caf4b0.png">

**Comment by gocanto** [comment]
Did you run bower install?

**Comment by ridislam** [comment]
problem solved..

**Comment by gocanto** [comment]
Was that the issue?

**Comment by ridislam** [comment]
yes, that's the issue.

**Comment by gocanto** [comment]
Good buddy. Please, let me know if you find something else.

**Comment by ridislam** [comment]
this is very good script, but I am thinking why the response is not well as
the script. this app need some finishing work left, that's the reason.
there are some bugs I have faced. after installation few features are not
working.I can see those issues are not available in the demo but those bugs
are in my installed project. ill send them when I get time. thanks

**Comment by gocanto** [comment]
Thanks for letting me know this. Are you able to pull off anlist with this festures? 

I dont know if you are aware but a I am rewritting the whola backend from scrash and would like to have some feedback.

**Comment by ridislam** [comment]
of course I will give my feedback. one thing I want to know. Are you using angular on the new app? and ill give my feedback soon..thanks

**Comment by gocanto** [comment]
I am working on the backend refactoring for now. Once it is done, i will star the front with Vue

**Comment by ridislam** [comment]
that will be awesome, I was hopping that you would use Vue not angular..that will be a great app.
