### ISSUE TITLE
ErrorException after standard User registration and Logged.

### ISSUE THREAD

**Issue by Kolovrat19** [ant-vel/App#25]
![image](https://cloud.githubusercontent.com/assets/11833474/26670770/a14ffe3e-46bb-11e7-93f1-9d3c8c38f581.png)

**Comment by gocanto** [comment]
Working on it

**Comment by gocanto** [comment]
Fixed https://github.com/ant-vel/Shop/releases/tag/1.0.14

Thanks for testing.
