### ISSUE TITLE
After installed, home page error

### ISSUE THREAD

**Issue by davisharry** [ant-vel/App#26]
After installed, both home page and the admin page went wrong. Here are the screenshot:
![error1](https://cloud.githubusercontent.com/assets/24517852/26739153/593b4902-4803-11e7-9150-6b13347fc83d.png)
![error2](https://cloud.githubusercontent.com/assets/24517852/26739160/5e6c61b8-4803-11e7-8f48-1f467a53cda3.png)

**Comment by gocanto** [comment]
Well, bear with me for a bit. I am working on the integrarions tests. 

PR's are welcome ✌🏼👨🏻‍💻

**Comment by davisharry** [comment]
I am so sorry. It's my problem. I forgot to generate the app-key. Sorry for bothering you.

**Comment by gocanto** [comment]
Dont worry. Keep me posted!! I will keep this issue open until I double check what's happening in here.

**Comment by davisharry** [comment]
The problem in the  first screenshot has solved when I change  php version from 5.6 to 7.0
