### ISSUE TITLE
Close the google recaptcha

### ISSUE THREAD

**Issue by davisharry** [ant-vel/App#27]
Since I am studying the code in my local environment and google it's unavailable in China. How can i close the google reCaptcha.

**Comment by davisharry** [comment]
Besides. I can not login as admin.
Even in the demo website antve.com/auth/login  using admin@antvel.com  admin.
In my localhost the login url it's localhost/login, different from the demo website.

**Comment by gocanto** [comment]
Hi, thanks for reaching out. 

This is the answer for the re-capcha issue: https://github.com/ant-vel/Shop/blob/master/src/User/Requests/LoginRequest.php#L41

In regard to your login issue, I recommend you to check the app seeders to find out about login access. 

Seeder: https://github.com/ant-vel/App/blob/master/database/seeds/UsersTableSeeder.php#L22
Factories: https://github.com/ant-vel/Shop/tree/master/database/factories

Thanks again.
