### ISSUE TITLE
Could not login as admin in online demo.

### ISSUE THREAD

**Issue by muyang** [ant-vel/App#30]
When I try to login with admin@antvel.com /admin, 
the information "These credentials do not match our records." pop up
But the register a new account and login, it will succeed.

Is there any suggestion for the problem?

**Comment by gocanto** [comment]
If the issue was with the demo page, it is meant to be like this. I had a problem once with somebody messing with it. Otherwise, you can control it yourself locally!

**Comment by muyang** [comment]
@gocanto yes, I installed antvel on ubuntu 16.04 and I run it locally

**Comment by gocanto** [comment]
Did you check the seeders?

**Comment by muyang** [comment]
@gocanto yes, i did, dear gocanto

**Comment by gocanto** [comment]
Ok, let me know whether it's working. Thanks!

**Comment by muyang** [comment]
@gocanto 
Dear gocanto, I still could not login as admin.

**Comment by gocanto** [comment]
Provide a wider explanation about your setup and configuration. Thanks

**Comment by muyang** [comment]
I did not install it with 'antvel installer'.:
1 git clone
2 cp .env.example and config key,database,and recaptcha v2 key
2 composer install. and bower install
3 php artisan migrate and php artisan db:seed
4 php artisan serve
Then it worked well except logining with admin, some times the login page shows recaptcha key is not valid.
Mayne I should try the antvel installer

**Comment by muyang** [comment]
@gocanto
Dear gocanto:
Is the default username: 'admin@antvel.com', and password 'admin' ?

I created a user and update the user table by modifying the 'role' value to 'admin ' for the new user.
Now I can login as admin with the new user

**Comment by gocanto** [comment]
Hi, 

for the re-captcha issue, you will have to register your Google keys.

The user seeder is here, you might want to take a look at it https://github.com/ant-vel/App/blob/master/database/seeds/UsersTableSeeder.php

Thanks.
