### ISSUE TITLE
Problem installing the App

### ISSUE THREAD

**Issue by svs22121990** [ant-vel/App#31]
Hi,

I am not able to install the app. Sometimes Tinker or Dusk files are missing. The migrations are also not working because of version issues and the angular bower js and css files are missing from the path.

FatalThrowableError
Class 'Laravel\Tinker\TinkerServiceProvider' not found

**Comment by gocanto** [comment]
Can you please post the errors?

**Comment by svs22121990** [comment]
Error 1 : After installing the app. Ticker also gets installed but, still I get below error.

FatalThrowableError
Class 'Laravel\Tinker\TinkerServiceProvider' not found

Some of the angular bower js and css are missing.

**Comment by gocanto** [comment]
Will check it soon. 

Thanks for testing

**Comment by svs22121990** [comment]
I am looking to use Antvel. Hope you can get back soon.

Thanks !

**Comment by gocanto** [comment]
I am working on some refactoring and will have it on github soon. Please, be patient! 

thanks for testing!

**Comment by gocanto** [comment]
Hey there, 

You might wanna check the new update and let me know whether you are still facing this issue. 

Thanks,

**Comment by svs22121990** [comment]
Hi,

The installation worked good. But, some migration files are missing. I have got below error.

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'stylon.product_pictures' doesn't exist (SQL: select * from `product_pictures` where `product_pictures`.`product_id` in (1, 2, 3, 4))

**Comment by gocanto** [comment]
Those files are located in the SHOP package. I guess you would have to do composer dumpautoload -o and try again. 

Let me know

**Comment by svs22121990** [comment]
I don't know know why but the migrations don't work and I get syntax error everytime. Anyways, so I manually created the product_pictures table and the script runs. But, it cannot find the required CSS & JS files of antvel-bower.

There is no antvel-bower folder of assets in public

![antvel](https://user-images.githubusercontent.com/26024356/28168499-ee248a42-67fc-11e7-9ed7-d18f89b9f9c4.png)

**Comment by gocanto** [comment]
Please, delete the vendor folder and make sure you have the latest version of the antvel/shop package. 

To solve the JS issues, you will have to install bower and then the antvel dependencies. 

Please, read the instalation steps for further references. 

Thanks for testing! 

:)
