### ISSUE TITLE
Problem whit products suggestions on PgSql

### ISSUE THREAD

**Issue by mrcoco** [ant-vel/App#32]
I have a problem when using PgSql on Product Suggestion.

> `SQLSTATE[22P02]:
> Invalid text representation: 7 ERROR: invalid input syntax for integer: "" (SQL: select distinct * from "products" where "id" not in (1, 2, 3, 4, 5, 6, 7, 8) and "status" = 1 and "stock" > 0 and "category_id" in () order by "rate_val" desc limit 4)`

for now i just comment suggestionsFor() on ProductsSuggestions to hide the error.

> `protected function products(string $type, array $constraints) : Collection
	{
		return Product::when( $this->except->count() > 0 , function($query) {
				return $query->whereNotIn('id', $this->except->all());
			})
			//->suggestionsFor($type, $constraints)
			->orderBy('rate_val', 'desc')
			->take($this->limit)
			->get();
	}`

**Comment by gocanto** [comment]
I am actually working on an issue there. I will commit soon! Thanks for testing

**Comment by gocanto** [comment]
Just published a new release. 

Check whether it fixes the issue, otherwise, you would have to give more info. :)

**Comment by mrcoco** [comment]
i still have same problem on "category_id" in () if using postgresql.

**Comment by gocanto** [comment]
Please share your set up to try reproducing your issue in my machine. 

Thanks

**Comment by mrcoco** [comment]
I just tried to fresh install with mysql and postgresql, This problem is only found in postgresql.
i use php7.1 and postgresql 9.6

**Comment by gocanto** [comment]
Ok.. can you share a screenshot with the full error track? 

Thanks

**Comment by mrcoco** [comment]
![screen shot 2017-07-23 at 10 36 32 pm](https://user-images.githubusercontent.com/377529/28500727-82e4d518-6ff7-11e7-89c1-d6bcf25eabde.png)

**Comment by mrcoco** [comment]
category_id is empty

**Comment by gocanto** [comment]
Ok, I see what the problem can be. I will be committing soon, stay tune.

**Comment by gocanto** [comment]
There is a new version of the shop package, can you try this out and let me know, please?

**Comment by gocanto** [comment]
It should be fixed now. I just add a validation to prevent this issue, also tests to back this up.

Thanks for testing.


https://github.com/ant-vel/Shop/commit/bf91e2b9f60308863c305e46e839033cf41e9af0
