### ISSUE TITLE
Two levels in "categories"

### ISSUE THREAD

**Issue by Kolovrat19** [ant-vel/App#35]
In the application implemented 2 levels of categories. It's not practical. In the final version, will you use unlimited depth?

**Comment by gocanto** [comment]
It is meant to be like that. The mentioned behavior just happens when listinf products, but will list recursivly 2 by 2. I am in the search to see how i can pull this off having a good performance :)

**Comment by Kolovrat19** [comment]
I also have a problem with the performance of the tree. Nested metnod works best. Fewer queries to the database. Can be used https://github.com/lazychaser/laravel-nestedset or https://github.com/etrepat/baum

**Comment by gocanto** [comment]
Yes i checked that package before but did not want to depend on a 3rd party one. If you have chance check the relation in category model. It is supposed to be recursive but laravel just give 2 ways deep using as 'parent.parent' 

Any thoughts?

**Comment by gocanto** [comment]
Let me look into it really well first. I need to finish something I am working in rn and I will start researching about this again. It is in my task list anyways. :)

**Comment by Kolovrat19** [comment]
Good luck.

**Comment by gocanto** [comment]
The issue has been addressed on https://github.com/ant-vel/Shop/commit/20f5ad685adebd824e0c6f026679fb14b2f7b777

Thanks for testing and pointing this out to me. 

Let me know your feedback.
