### ISSUE TITLE
Getting started issues. 

### ISSUE THREAD

**Issue by codeitlikemiley** [ant-vel/App#37]
i try to install in new laravel app, then do antvel install
then it give me this error
how to fix this?

**Comment by gocanto** [comment]
What error buddy?

**Comment by codeitlikemiley** [comment]
on laravel valet i did have https , but dont know why this pop out
```
[GuzzleHttp\Exception\RequestException]
  cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)
```

**Comment by gocanto** [comment]
This seems to be an error related to ur https certificate. Did you google it or see how https is managed with valet? 

On the another hand, if you want to install antvel this way, you have to pull in the shop package through composer as it is done within the app composer file.

**Comment by gocanto** [comment]
Anyways, the best way to install antvel for now is clonning this repo and running composer install. I am still working on some integrations goodies :)

**Comment by codeitlikemiley** [comment]
ive check composer.json its still the default, may i know what package i need to require?

**Comment by codeitlikemiley** [comment]
ok ill clone it thanks

**Comment by gocanto** [comment]
Let's keep this issue open so you can keep me posted it. I am still working on the integration and would like to know what approach is the best.

**Comment by gocanto** [comment]
Related https://github.com/ant-vel/Installer/issues/2#issuecomment-328283261


=== 
Opened for suggestions!

**Comment by gocanto** [comment]
This bug was fixed with the latest releases which can be found on https://github.com/ant-vel/Installer/releases/tag/1.0.5

Also, the readme file was updated with some of the steps to be executed by the user when installing the app throughout the installer

Thanks for testing.

Remember to keep me posted with your feedback.
