### ISSUE TITLE
failed admin login

### ISSUE THREAD

**Issue by mrcoco** [ant-vel/App#38]
I have failed login after update, with user admin@antvel.com and password 123456

**Comment by gocanto** [comment]
Do you have the latest release?

**Comment by mrcoco** [comment]
I have the last update from github and updated composer

**Comment by gocanto** [comment]
I just tested it out and it worked for me. I would recommend you to run ```composer clear-cache``` and then ```composer update``` to have the latest ```ant-vel/shop``` package release.

Let me know how it goes for you because I couldn't reproduce the error you are facing.

Thanks.

**Comment by mrcoco** [comment]
it turns out I have not updated the database in the factory seeder about changing the verified value to true. done with artisan migrate:fresh

**Comment by gocanto** [comment]
Cool, thanks for testing.
