### ISSUE TITLE
command vendor:publish does not work ServiceProvider of Ant-vel/Shop 

### ISSUE THREAD

**Issue by oasis1992** [ant-vel/App#45]
I set the environment variable but I can not make it work, I'm using Mac Os Sierra

**Comment by gocanto** [comment]
share errors please

**Comment by oasis1992** [comment]
Sorry I was confused about the project, but I downloaded this project. when executing the command php artisan vendor: publish ... the migrations, routes and others. they do not move to the project

**Comment by gocanto** [comment]
they are not meant to be moved to it.

**Comment by oasis1992** [comment]
Is there any instruction?

**Comment by gocanto** [comment]
U need to install the main app, then run composer install from there within the command line.
