### ISSUE TITLE
Logo proporsal requests

### ISSUE THREAD

**Issue by LuigiBaute** [ant-vel/App#50]
Hello good afternoon I would like to collaborate with your project, I can design the logo of your project or renew it if you already have one, for free

**Comment by maxence-charriere** [comment]
Hello @LuigiBaute, thanks for offering your help.
I'm pretty satisfied with the current logo, but I'm open to new ideas that would better represent the project.
Feel free to contact me if you think about something or if you have some mocks.

**Comment by gocanto** [comment]
Ok, send me an email. My info is on the project readme

**Comment by LuigiBaute** [comment]
![logotipo antvel](https://user-images.githubusercontent.com/36426974/39806592-45b0d4a0-5348-11e8-863a-a0a0f77f8e93.jpg)

Greetings @gocanto tell me if you liked any of the logos, any suggestions? I'll gladly do some changes if necessary :)

**Comment by gocanto** [comment]
They look really awesome, but I am looking for some extremely simple that shows what the product is. 

Something along these lines. Thanks tho

![image](https://user-images.githubusercontent.com/5246059/39807619-563bfaf4-53af-11e8-8ed8-f8e5561d3944.png)

**Comment by gocanto** [comment]
de que parte de Venezuela eres?

**Comment by LuigiBaute** [comment]
De Carabobo, Valencia. Saludos!

**Comment by LuigiBaute** [comment]
Presentaré una nueva propuesta simplificada.

**Comment by gocanto** [comment]
Yo soy de guacara. Gracias :)

**Comment by LuigiBaute** [comment]
![logotipo antvel2](https://user-images.githubusercontent.com/36426974/39903884-5ab98bd8-54a3-11e8-9015-c535fb38bc9e.jpg)

Hola, @gocanto Esta vez intenté hacer referencia al ''comercio electrónico'', espero que te guste...
