### ISSUE TITLE
Implemented The Core Help Needed

### ISSUE THREAD

**Issue by zymawy** [ant-vel/App#54]
Hi 
Thank You For This Amazing Work, 
I Have Implemented The Core Of The Antval. *_**I Did Not Clone This Repo**_*
Now, I Have My Own Category Model And I Have Extend `Antvel\Categories\Models\Category`
If I Insert Know Category It's Inserted Successfully But, It's Not Appearing In The Index And Also The Image Not Uploaded. I May Missing Something!?

**Comment by gocanto** [comment]
well, this pkg was not meant to be extended. Sorry about that =)

**Comment by zymawy** [comment]
Totally, Understood

**Comment by zymawy** [comment]
Ceruse How Did You Save The Image In Storage Folder And Not Inside storage/app/public. And Even Tho Still Visible?
