### ISSUE TITLE
Antvel installer error

### ISSUE THREAD

**Issue by roots225** [ant-vel/App#55]
Hello,
I want try antvel but i get this error using antvel installer

Fatal error: Uncaught Error: Class 'Symfony\Component\Console\Application' not found in C:\Users\LENOVO\AppData\Roaming\Composer\vendor\antvel\installer\antvel:9
Stack trace:
#0 {main}
  thrown in C:\Users\LENOVO\AppData\Roaming\Composer\vendor\antvel\installer\antvel on line 9
please help thanks.

**Comment by gocanto** [comment]
Here is the work out for this.
https://github.com/ant-vel/App/issues/9#issuecomment-413162799

Thanks,
