### ISSUE TITLE
Database error

### ISSUE THREAD

**Issue by devabhijit13** [ant-vel/App#58]
There is only one file in databsa/migration.

When i run php artisan migration command i get following errors.
C:\xampp\htdocs\App-master>php artisan migrate

   Illuminate\Database\QueryException  : SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'json null, `verified` tinyint(1) not null default '0', `confirmation_token` varc' at line 1 (SQL: create table `users` (`id` int unsigned not null auto_increment primary key, `first_name` varchar(60) not null, `last_name` varchar(60) not null, `nickname` varchar(60) not null, `email` varchar(100) not null, `password` varchar(60) not null, `role` enum('admin', 'seller', 'customer') not null default 'customer', `phone_number` varchar(20) null, `gender` enum('female', 'male') not null default 'male', `birthday` date null, `image` text null, `facebook` varchar(100) null, `twitter` varchar(100) null, `website` varchar(100) null, `language` varchar(10) not null default 'en', `time_zone` varchar(60) null, `description` varchar(150) null, `rate_val` int null, `rate_count` int null, `preferences` json null, `verified` tinyint(1) not null default '0', `confirmation_token` varchar(60) null, `remember_token` varchar(100) null, `created_at` timestamp null, `updated_at` timestamp null, `disabled_at` timestamp null, `deleted_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci')

  at C:\xampp\htdocs\App-master\vendor\laravel\framework\src\Illuminate\Database\Connection.php:664
    660|         // If an exception occurs when attempting to run a query, we'll format the error
    661|         // message to include the bindings with SQL, which will make this exception a
    662|         // lot more helpful to the developer instead of just the database's errors.
    663|         catch (Exception $e) {
  > 664|             throw new QueryException(
    665|                 $query, $this->prepareBindings($bindings), $e
    666|             );
    667|         }
    668|

  Exception trace:

  1   PDOException::("SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'json null, `verified` tinyint(1) not null default '0', `confirmation_token` varc' at line 1")
      C:\xampp\htdocs\App-master\vendor\laravel\framework\src\Illuminate\Database\Connection.php:452

  2   PDO::prepare("create table `users` (`id` int unsigned not null auto_increment primary key, `first_name` varchar(60) not null, `last_name` varchar(60) not null, `nickname` varchar(60) not null, `email` varchar(100) not null, `password` varchar(60) not null, `role` enum('admin', 'seller', 'customer') not null default 'customer', `phone_number` varchar(20) null, `gender` enum('female', 'male') not null default 'male', `birthday` date null, `image` text null, `facebook` varchar(100) null, `twitter` varchar(100) null, `website` varchar(100) null, `language` varchar(10) not null default 'en', `time_zone` varchar(60) null, `description` varchar(150) null, `rate_val` int null, `rate_count` int null, `preferences` json null, `verified` tinyint(1) not null default '0', `confirmation_token` varchar(60) null, `remember_token` varchar(100) null, `created_at` timestamp null, `updated_at` timestamp null, `disabled_at` timestamp null, `deleted_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'")
      C:\xampp\htdocs\App-master\vendor\laravel\framework\src\Illuminate\Database\Connection.php:452

Please advise.

**Comment by gocanto** [comment]
Did you run compose install ?

**Comment by devabhijit13** [comment]
yes

**Comment by gocanto** [comment]
This issue is duplicated.
You can read more about it on https://github.com/ant-vel/App/issues/47

Thanks
