### ISSUE TITLE
package not found for PHP 5.6

### ISSUE THREAD

**Issue by fadynoor** [ant-vel/App#8]
i got this message when insttalling with composer 

>  [InvalidArgumentException]
>   Could not find package antvel/installer at any version matching your PHP version 5.6.28.0

**Comment by gocanto** [comment]
Did you try installing with the installer?

**Comment by gocanto** [comment]
That's is due to https://github.com/ant-vel/Installer/blob/master/composer.json#L21

Thanks for testing.
